spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog_app_4
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
server:
  port: 8080
